### PR TITLE
Create index.ko.md

### PR DESCRIPTION
**Pull request by webix**

### CODE REVIEW

**Comment by levonet** [comment]
\cc @tadatuta

**Comment by tadatuta** [comment]
unfortunately we don't have possibility to support partial translations on bem.info right now.
we're going to invent something in the next major version. so let this pull request hang until we find a sollution.

**Comment by zxqfox** [comment]
Can it will be solved with fallback language? Or troubles with building all of them into one?

**Comment by tadatuta** [comment]
@zxqfox there's also an issue with versioning and consistency

**Comment by webix** [comment]
I will just translate some docs or files into Korean for instroducing BEM mothod with origin resources and give some guidace to our colleagues before that.But will be slow, and couldn't translate entires alone,  sorry for this.

**Pull request closed without merging**
